services:
  - type: web
    name: avellano-chatbot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
    port: 3000